[project]
name = "fibre-image"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "ipython>=9.1.0",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "qutip>=5.1.1",
    "tensorflow>=2.19.0",
]
